<a href="https://colab.research.google.com/github/munawirmt/prediction-models/blob/main/black_friday_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EDA & FEATURE ENGINEERING (BLACK FRIDAY DATASET)**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
## load train dataset from drive
from google.colab import drive
drive.mount("/content/drive")
file_path="/content/drive/MyDrive/black friday dataset/train-selected-columns.csv"
df_train=pd.read_csv(file_path)
df_train.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
##import test dataset from drive
file_path="/content/drive/MyDrive/black friday dataset/test-selected-columns.csv"
df_test=pd.read_csv(file_path)
df_test.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## merge train and test datasets
df= pd.concat([df_train, df_test], ignore_index=True)
df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26673 entries, 0 to 26672
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User_ID                     0 non-null      float64
 1   Product_ID                  0 non-null      float64
 2   Gender                      0 non-null      float64
 3   Age                         0 non-null      float64
 4   Occupation                  0 non-null      float64
 5   City_Category               0 non-null      float64
 6   Stay_In_Current_City_Years  0 non-null      float64
 7   Marital_Status              0 non-null      float64
 8   Product_Category_1          0 non-null      float64
 9   Product_Category_2          0 non-null      float64
dtypes: float64(10)
memory usage: 2.0 MB

In [ ]:
df.describe()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## remove user_id
print("Current columns in df:", df.columns.tolist())
# Strip whitespace from column names to handle potential invisible characters
df.columns = df.columns.str.strip()
if 'User_ID' in df.columns:
    df.drop(['User_ID'], axis=1, inplace=True)
    print("User_ID column dropped successfully.")
else:
    print("User_ID column not found after stripping whitespace. Please check the exact column name.")

Current columns in df: ['Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category', 'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1', 'Product_Category_2']
User_ID column not found after stripping whitespace. Please check the exact column name.

In [ ]:
df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## handle categorical feature gender
df['Gender']= df['Gender'].map({'F':0, 'M':1})

In [ ]:
## Combine Product_Category_1 and Product_Category_2 into a 'Purchase' column
# Assuming 'combine' means sum, as both are float types, but they are currently all NaN.
df['Purchase'] = df['Product_Category_1'] + df['Product_Category_2']

# Visualize 'Purchase' vs 'Age' barplot
import matplotlib.pyplot as plt
import seaborn as sns

if 'Age' in df.columns and not df['Age'].isnull().all() and \
   'Purchase' in df.columns and not df['Purchase'].isnull().all():
    plt.figure(figsize=(10, 6))
    sns.barplot(x='Age', y='Purchase', data=df, errorbar=None)
    plt.title('Average Purchase by Age Group')
    plt.xlabel('Age Group')
    plt.ylabel('Average Purchase')
    plt.show()
else:
    print("Cannot create barplot: 'Age' or 'Purchase' column is missing or entirely null. Please re-check data loading and column content.")

Cannot create barplot: 'Age' or 'Purchase' column is missing or entirely null. Please re-check data loading and column content.

In [ ]:
"""
## other method to handle categorical feature age

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Age']= label_encoder.fit_transform(df['Age'])
df['Age'].unique()
"""

"\n## other method to handle categorical feature age\n\nfrom sklearn import preprocessing\nlabel_encoder = preprocessing.LabelEncoder()\ndf['Age']= label_encoder.fit_transform(df['Age'])\ndf['Age'].unique()\n"

In [ ]:
## handle categorical feature city_category
df_city = pd.get_dummies(df['City_Category'], drop_first=True)
df_city.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
## add both
df = pd.concat([df, df_city], axis=1)
df.head()

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2
0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## delete city category
df.drop(['City_Category'], axis=1, inplace=True)
df.head()

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2
0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN

In [ ]:
## missing values
df.isnull().sum()

Product_ID                    26673
Gender                        26673
Age                               0
Occupation                    26673
Stay_In_Current_City_Years    26673
Marital_Status                26673
Product_Category_1            26673
Product_Category_2            26673
dtype: int64

In [ ]:
## focus on replacing missing values (category 1,2)
df['Product_Category_1'].unique() ## descrete feature
df['Product_Category_2'].unique() ## descrete feature

df['Product_Category_2'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
## replace missing values with mode (best way to descrete feature)
df['Product_Category_2'].mode()
df['Product_Category_2'] = df['Product_Category_2'].fillna(df['Product_Category_2'])
df['Product_Category_2'].isnull().sum()

np.int64(26673)

In [ ]:
df['Product_Category_1'].mode()
df['Product_Category_1'] = df['Product_Category_2'].fillna(df['Product_Category_1'])
df['Product_Category_1'].isnull().sum()

np.int64(26673)

In [ ]:
df.head()

,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2
0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(26673, 8)

In [ ]:
df['Stay_In_Current_City_Years'].unique()
# Convert the column to string type before using .str accessor
df['Stay_In_Current_City_Years'] = df['Stay_In_Current_City_Years'].astype(str).str.replace('+', '', regex=False)
df['Stay_In_Current_City_Years']

0        nan
1        nan
2        nan
3        nan
4        nan
        ...
26668    nan
26669    nan
26670    nan
26671    nan
26672    nan
Name: Stay_In_Current_City_Years, Length: 26673, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26673 entries, 0 to 26672
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  0 non-null      float64
 1   Gender                      0 non-null      float64
 2   Age                         26673 non-null  int64
 3   Occupation                  0 non-null      float64
 4   Stay_In_Current_City_Years  26673 non-null  object
 5   Marital_Status              0 non-null      float64
 6   Product_Category_1          0 non-null      float64
 7   Product_Category_2          0 non-null      float64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.6+ MB

In [ ]:
## convert uint8 to int
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26673 entries, 0 to 26672
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product_ID                  0 non-null      float64
 1   Gender                      0 non-null      float64
 2   Age                         26673 non-null  int64
 3   Occupation                  0 non-null      float64
 4   Stay_In_Current_City_Years  26673 non-null  object
 5   Marital_Status              0 non-null      float64
 6   Product_Category_1          0 non-null      float64
 7   Product_Category_2          0 non-null      float64
dtypes: float64(6), int64(1), object(1)
memory usage: 1.6+ MB

In [ ]:
## visualization age vs purchase
if 'Purchase' in df.columns and not df['Purchase'].isnull().all():
    sns.barplot(x='Age', y='Purchase', hue='Gender', data=df)
else:
    print("Cannot create barplot: 'Purchase' column is missing or entirely null. Please re-check data loading.")

Cannot create barplot: 'Purchase' column is missing or entirely null. Please re-check data loading.