<a href="https://colab.research.google.com/github/munawirmt/prediction-models/blob/main/flight_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# F**LIGHT PRICE PREDICTION (EDA & FEATURE ENGINEERING)**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
## load dataset
from google.colab import drive
drive.mount('/content/drive')
file_path="/content/drive/MyDrive/flight prediction/Data_Train.xlsx"
df_train=pd.read_excel(file_path)
df_train.head()

Mounted at /content/drive

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [ ]:
df_train.shape

(10683, 11)

In [ ]:
file_path="/content/drive/MyDrive/flight prediction/Test_set.xlsx"
df_test=pd.read_excel(file_path)
df_test.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [ ]:
df_test.shape

(2671, 10)

In [ ]:
final_df=pd.merge(df_train,df_test,how='outer')
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,Air Asia,01/03/2019,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,10715.0
1,Air Asia,01/03/2019,Banglore,New Delhi,BLR → DEL,23:25,02:10 02 Mar,2h 45m,non-stop,Red-eye flight,10873.0
2,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7074.0
3,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7652.0
4,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,23:25,02:10 04 Mar,2h 45m,non-stop,No info,6135.0

In [ ]:
final_df.shape

(13151, 11)

In [ ]:
final_df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
13146,Vistara Premium economy,03/03/2019,Banglore,New Delhi,BLR → DEL,09:50,12:35,2h 45m,non-stop,No info,NaN
13147,Vistara Premium economy,03/03/2019,Banglore,New Delhi,BLR → DEL,16:00,18:35,2h 35m,non-stop,No info,11793.0
13148,Vistara Premium economy,1/03/2019,Chennai,Kolkata,MAA → CCU,07:05,09:20,2h 15m,non-stop,No info,9125.0
13149,Vistara Premium economy,24/03/2019,Banglore,New Delhi,BLR → DEL,19:40,22:20,2h 40m,non-stop,No info,NaN
13150,Vistara Premium economy,6/04/2019,Banglore,Delhi,BLR → DEL,11:30,14:20,2h 50m,non-stop,No info,5969.0

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13151 entries, 0 to 13150
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13151 non-null  object
 1   Date_of_Journey  13151 non-null  object
 2   Source           13151 non-null  object
 3   Destination      13151 non-null  object
 4   Route            13150 non-null  object
 5   Dep_Time         13151 non-null  object
 6   Arrival_Time     13151 non-null  object
 7   Duration         13151 non-null  object
 8   Total_Stops      13150 non-null  object
 9   Additional_Info  13151 non-null  object
 10  Price            10697 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.1+ MB

In [ ]:
## feature engineering process
final_df['Date']=final_df['Date_of_Journey'].str.split('/').str[0]
final_df['Month']=final_df['Date_of_Journey'].str.split('/').str[1]
final_df['Year']=final_df['Date_of_Journey'].str.split('/').str[2]
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,Air Asia,01/03/2019,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,10715.0,01,03,2019
1,Air Asia,01/03/2019,Banglore,New Delhi,BLR → DEL,23:25,02:10 02 Mar,2h 45m,non-stop,Red-eye flight,10873.0,01,03,2019
2,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7074.0,03,03,2019
3,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7652.0,03,03,2019
4,Air Asia,03/03/2019,Banglore,New Delhi,BLR → DEL,23:25,02:10 04 Mar,2h 45m,non-stop,No info,6135.0,03,03,2019

In [ ]:
final_df['Date']=final_df['Date'].astype(int)
final_df['Month']=final_df['Month'].astype(int)
final_df['Year']=final_df['Year'].astype(int)
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13151 entries, 0 to 13150
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13151 non-null  object
 1   Date_of_Journey  13151 non-null  object
 2   Source           13151 non-null  object
 3   Destination      13151 non-null  object
 4   Route            13150 non-null  object
 5   Dep_Time         13151 non-null  object
 6   Arrival_Time     13151 non-null  object
 7   Duration         13151 non-null  object
 8   Total_Stops      13150 non-null  object
 9   Additional_Info  13151 non-null  object
 10  Price            10697 non-null  float64
 11  Date             13151 non-null  int64
 12  Month            13151 non-null  int64
 13  Year             13151 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 1.4+ MB

In [ ]:
final_df.drop('Date_of_Journey',axis=1,inplace=True)
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,10715.0,1,3,2019
1,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,02:10 02 Mar,2h 45m,non-stop,Red-eye flight,10873.0,1,3,2019
2,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7074.0,3,3,2019
3,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7652.0,3,3,2019
4,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,02:10 04 Mar,2h 45m,non-stop,No info,6135.0,3,3,2019

In [ ]:
final_df['Arrival_Time']=final_df['Arrival_Time'].str.split(' ').str[0]
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,10715.0,1,3,2019
1,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,02:10,2h 45m,non-stop,Red-eye flight,10873.0,1,3,2019
2,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7074.0,3,3,2019
3,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7652.0,3,3,2019
4,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,02:10,2h 45m,non-stop,No info,6135.0,3,3,2019

In [ ]:
final_df.isnull().sum()

Airline               0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2454
Date                  0
Month                 0
Year                  0
dtype: int64

In [ ]:
final_df['Arrival_hour']=final_df['Arrival_Time'].str.split(':').str[0]
final_df['Arrival_min']=final_df['Arrival_Time'].str.split(':').str[1]
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min
0,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,10715.0,1,3,2019,08,40
1,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,02:10,2h 45m,non-stop,Red-eye flight,10873.0,1,3,2019,02,10
2,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7074.0,3,3,2019,08,40
3,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,08:40,2h 50m,non-stop,No info,7652.0,3,3,2019,08,40
4,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,02:10,2h 45m,non-stop,No info,6135.0,3,3,2019,02,10

In [ ]:
final_df['Arrival_hour']=final_df['Arrival_hour'].astype(int)
final_df['Arrival_min']=final_df['Arrival_min'].astype(int)
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13151 entries, 0 to 13150
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13151 non-null  object
 1   Source           13151 non-null  object
 2   Destination      13151 non-null  object
 3   Route            13150 non-null  object
 4   Dep_Time         13151 non-null  object
 5   Duration         13151 non-null  object
 6   Total_Stops      13150 non-null  object
 7   Additional_Info  13151 non-null  object
 8   Price            10697 non-null  float64
 9   Date             13151 non-null  int64
 10  Month            13151 non-null  int64
 11  Year             13151 non-null  int64
 12  Arrival_hour     13151 non-null  int64
 13  Arrival_min      13151 non-null  int64
 14  Dep_hour         13151 non-null  object
 15  Dep_min          13151 non-null  object
dtypes: float64(1), int64(5), object(10)
memory usage: 1.6+ MB

In [ ]:
final_df.drop('Arrival_Time',axis=1,inplace=True)
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min
0,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,2h 50m,non-stop,No info,10715.0,1,3,2019,08,40
1,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,2h 45m,non-stop,Red-eye flight,10873.0,1,3,2019,02,10
2,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,2h 50m,non-stop,No info,7074.0,3,3,2019,08,40
3,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,2h 50m,non-stop,No info,7652.0,3,3,2019,08,40
4,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,2h 45m,non-stop,No info,6135.0,3,3,2019,02,10

In [ ]:
## do it for departure time also
final_df['Dep_Time']=final_df['Dep_Time'].str.split(' ').str[0]
final_df['Dep_hour']=final_df['Dep_Time'].str.split(':').str[0]
final_df['Dep_min']=final_df['Dep_Time'].str.split(':').str[1]
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,2h 50m,non-stop,No info,10715.0,1,3,2019,08,40,05,50
1,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,2h 45m,non-stop,Red-eye flight,10873.0,1,3,2019,02,10,23,25
2,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,2h 50m,non-stop,No info,7074.0,3,3,2019,08,40,05,50
3,Air Asia,Banglore,New Delhi,BLR → DEL,05:50,2h 50m,non-stop,No info,7652.0,3,3,2019,08,40,05,50
4,Air Asia,Banglore,New Delhi,BLR → DEL,23:25,2h 45m,non-stop,No info,6135.0,3,3,2019,02,10,23,25

In [ ]:
final_df['Dep_hour']=final_df['Dep_hour'].astype(int)
final_df['Dep_min']=final_df['Dep_min'].astype(int)
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13151 entries, 0 to 13150
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13151 non-null  object
 1   Source           13151 non-null  object
 2   Destination      13151 non-null  object
 3   Route            13150 non-null  object
 4   Duration         13151 non-null  object
 5   Total_Stops      13150 non-null  object
 6   Additional_Info  13151 non-null  object
 7   Price            10697 non-null  float64
 8   Date             13151 non-null  int64
 9   Month            13151 non-null  int64
 10  Year             13151 non-null  int64
 11  Arrival_hour     13151 non-null  int64
 12  Arrival_min      13151 non-null  int64
 13  Dep_hour         13151 non-null  int64
 14  Dep_min          13151 non-null  int64
dtypes: float64(1), int64(7), object(7)
memory usage: 1.5+ MB

In [ ]:
final_df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,Air Asia,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,10715.0,1,3,2019,8,40,5,50
1,Air Asia,Banglore,New Delhi,BLR → DEL,2h 45m,non-stop,Red-eye flight,10873.0,1,3,2019,2,10,23,25
2,Air Asia,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,7074.0,3,3,2019,8,40,5,50
3,Air Asia,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,7652.0,3,3,2019,8,40,5,50
4,Air Asia,Banglore,New Delhi,BLR → DEL,2h 45m,non-stop,No info,6135.0,3,3,2019,2,10,23,25

In [ ]:
final_df['Total_Stops'].unique()

array(['non-stop', '1 stop', '2 stops', '3 stops', '4 stops', nan],
      dtype=object)

In [ ]:
final_df['Total_Stops']=final_df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4,'nan':1})
final_df[final_df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,Air Asia,Banglore,New Delhi,BLR → DEL,2h 50m,NaN,No info,10715.0,1,3,2019,8,40,5,50
1,Air Asia,Banglore,New Delhi,BLR → DEL,2h 45m,NaN,Red-eye flight,10873.0,1,3,2019,2,10,23,25
2,Air Asia,Banglore,New Delhi,BLR → DEL,2h 50m,NaN,No info,7074.0,3,3,2019,8,40,5,50
3,Air Asia,Banglore,New Delhi,BLR → DEL,2h 50m,NaN,No info,7652.0,3,3,2019,8,40,5,50
4,Air Asia,Banglore,New Delhi,BLR → DEL,2h 45m,NaN,No info,6135.0,3,3,2019,2,10,23,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13146,Vistara Premium economy,Banglore,New Delhi,BLR → DEL,2h 45m,NaN,No info,NaN,3,3,2019,12,35,9,50
13147,Vistara Premium economy,Banglore,New Delhi,BLR → DEL,2h 35m,NaN,No info,11793.0,3,3,2019,18,35,16,0
13148,Vistara Premium economy,Chennai,Kolkata,MAA → CCU,2h 15m,NaN,No info,9125.0,1,3,2019,9,20,7,5
13149,Vistara Premium economy,Banglore,New Delhi,BLR → DEL,2h 40m,NaN,No info,NaN,24,3,2019,22,20,19,40
13150,Vistara Premium economy,Banglore,Delhi,BLR → DEL,2h 50m,NaN,No info,5969.0,6,4,2019,14,20,11,30

In [ ]:
## final_df.drop('Route',axis=1,inplace=True) already did it
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13151 entries, 0 to 13150
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13151 non-null  object
 1   Source           13151 non-null  object
 2   Destination      13151 non-null  object
 3   Duration         13151 non-null  object
 4   Total_Stops      0 non-null      float64
 5   Additional_Info  13151 non-null  object
 6   Price            10697 non-null  float64
 7   Date             13151 non-null  int64
 8   Month            13151 non-null  int64
 9   Year             13151 non-null  int64
 10  Arrival_hour     13151 non-null  int64
 11  Arrival_min      13151 non-null  int64
 12  Dep_hour         13151 non-null  int64
 13  Dep_min          13151 non-null  int64
dtypes: float64(2), int64(7), object(5)
memory usage: 1.4+ MB

In [ ]:
final_df['Additional_Info'].unique()

array(['No info', 'Red-eye flight', '1 Long layover', '2 Long layover',
       '1 Short layover', 'Change airports', 'No Info', 'Business class',
       'In-flight meal not included', 'No check-in baggage included'],
      dtype=object)

In [ ]:
## convert hour to minute
final_df['duration_hour']=final_df['Duration'].str.split(' ').str[0].str.split('h').str[0]
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour
0,Air Asia,Banglore,New Delhi,2h 50m,NaN,No info,10715.0,1,3,2019,8,40,5,50,2
1,Air Asia,Banglore,New Delhi,2h 45m,NaN,Red-eye flight,10873.0,1,3,2019,2,10,23,25,2
2,Air Asia,Banglore,New Delhi,2h 50m,NaN,No info,7074.0,3,3,2019,8,40,5,50,2
3,Air Asia,Banglore,New Delhi,2h 50m,NaN,No info,7652.0,3,3,2019,8,40,5,50,2
4,Air Asia,Banglore,New Delhi,2h 45m,NaN,No info,6135.0,3,3,2019,2,10,23,25,2

In [ ]:
final_df[final_df['duration_hour']=='5m']

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour
767,Air India,Mumbai,Hyderabad,5m,NaN,No info,NaN,12,3,2019,16,55,16,50,5m
2089,Air India,Mumbai,Hyderabad,5m,NaN,No info,17327.0,6,3,2019,16,55,16,50,5m

In [ ]:
def extract_duration_parts(duration_str):
    hours = 0
    minutes = 0
    duration_str = str(duration_str) # Ensure it's a string to prevent errors with non-string types

    # Check for hours
    if 'h' in duration_str:
        h_part = duration_str.split('h')[0].strip()
        try:
            hours = int(h_part)
        except ValueError:
            pass # If conversion fails, hours remains 0

        # Check for minutes after 'h'
        if 'm' in duration_str.split('h')[-1]:
            m_part = duration_str.split('h')[-1].split('m')[0].strip()
            try:
                minutes = int(m_part)
            except ValueError:
                pass # If conversion fails, minutes remains 0
    # Check for minutes if no 'h' was found in the main part
    elif 'm' in duration_str:
        m_part = duration_str.split('m')[0].strip()
        try:
            minutes = int(m_part)
        except ValueError:
            pass # If conversion fails, minutes remains 0

    return hours, minutes

# Apply the function to create new 'duration_hour' and 'duration_min' columns
final_df[['duration_hour', 'duration_min']] = final_df['Duration'].apply(lambda x: pd.Series(extract_duration_parts(x)))

# Ensure they are of integer type (though the function already tries to convert them)
final_df['duration_hour'] = final_df['duration_hour'].astype(int)
final_df['duration_min'] = final_df['duration_min'].astype(int)

# Drop the original 'Duration' column
final_df.drop('Duration', axis=1, inplace=True)

In [ ]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour,duration_min
0,Air Asia,Banglore,New Delhi,NaN,No info,10715.0,1,3,2019,8,40,5,50,2,50
1,Air Asia,Banglore,New Delhi,NaN,Red-eye flight,10873.0,1,3,2019,2,10,23,25,2,45
2,Air Asia,Banglore,New Delhi,NaN,No info,7074.0,3,3,2019,8,40,5,50,2,50
3,Air Asia,Banglore,New Delhi,NaN,No info,7652.0,3,3,2019,8,40,5,50,2,50
4,Air Asia,Banglore,New Delhi,NaN,No info,6135.0,3,3,2019,2,10,23,25,2,45

In [ ]:
# Reconstruct the 'Total_Stops' column from df_train and df_test
# First, concatenate the 'Total_Stops' columns from the original dataframes
total_stops_series = pd.concat([df_train['Total_Stops'], df_test['Total_Stops']], ignore_index=True)

# Define the mapping dictionary
stop_mapping = {'non-stop': 0, '1 stop': 1, '2 stops': 2, '3 stops': 3, '4 stops': 4}

# Apply the mapping to the reconstructed series
final_df['Total_Stops'] = total_stops_series.map(stop_mapping)

# Fill NaN values. The previous agent's attempt mapped 'nan' to 1,
# so we assume this is the desired behavior for any unmapped or original NaN values.
final_df['Total_Stops'].fillna(1, inplace=True)

# Convert to integer type
final_df['Total_Stops'] = final_df['Total_Stops'].astype(int)

# Display head and info to verify
display(final_df.head())
final_df.info()

/tmp/ipykernel_1212/4268490501.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df['Total_Stops'].fillna(1, inplace=True)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour,duration_min
0,Air Asia,Banglore,New Delhi,0,No info,10715.0,1,3,2019,8,40,5,50,2,50
1,Air Asia,Banglore,New Delhi,2,Red-eye flight,10873.0,1,3,2019,2,10,23,25,2,45
2,Air Asia,Banglore,New Delhi,2,No info,7074.0,3,3,2019,8,40,5,50,2,50
3,Air Asia,Banglore,New Delhi,1,No info,7652.0,3,3,2019,8,40,5,50,2,50
4,Air Asia,Banglore,New Delhi,1,No info,6135.0,3,3,2019,2,10,23,25,2,45

<class 'pandas.core.frame.DataFrame'>
Index: 13149 entries, 0 to 13150
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13149 non-null  object
 1   Source           13149 non-null  object
 2   Destination      13149 non-null  object
 3   Total_Stops      13149 non-null  int64
 4   Additional_Info  13149 non-null  object
 5   Price            10695 non-null  float64
 6   Date             13149 non-null  int64
 7   Month            13149 non-null  int64
 8   Year             13149 non-null  int64
 9   Arrival_hour     13149 non-null  int64
 10  Arrival_min      13149 non-null  int64
 11  Dep_hour         13149 non-null  int64
 12  Dep_min          13149 non-null  int64
 13  duration_hour    13149 non-null  int64
 14  duration_min     13149 non-null  int64
dtypes: float64(1), int64(10), object(4)
memory usage: 2.1+ MB

In [ ]:
final_df['Airline'].unique()

array(['Air Asia', 'Air India', 'GoAir', 'IndiGo', 'Jet Airways',
       'Jet Airways Business', 'Multiple carriers',
       'Multiple carriers Premium economy', 'SpiceJet', 'Trujet',
       'Vistara', 'Vistara Premium economy'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()

final_df['Airline']=labelencoder.fit_transform(final_df['Airline'])
final_df['Source']=labelencoder.fit_transform(final_df['Source'])
final_df['Destination']=labelencoder.fit_transform(final_df['Destination'])
final_df['Additional_Info']=labelencoder.fit_transform(final_df['Additional_Info'])

In [ ]:
final_df.shape

(13149, 15)

In [ ]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour,duration_min
0,0,0,5,0,8,10715.0,1,3,2019,8,40,5,50,2,50
1,0,0,5,2,9,10873.0,1,3,2019,2,10,23,25,2,45
2,0,0,5,2,8,7074.0,3,3,2019,8,40,5,50,2,50
3,0,0,5,1,8,7652.0,3,3,2019,8,40,5,50,2,50
4,0,0,5,1,8,6135.0,3,3,2019,2,10,23,25,2,45

In [ ]:
## labelencoder can do same by using onehotencoder

In [ ]:
pd.get_dummies(final_df,columns=['Airline','Source','Destination','Additional_Info'],drop_first=True)

,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour,...,Destination_5,Additional_Info_1,Additional_Info_2,Additional_Info_3,Additional_Info_4,Additional_Info_5,Additional_Info_6,Additional_Info_7,Additional_Info_8,Additional_Info_9
0,0,10715.0,1,3,2019,8,40,5,50,2,...,True,False,False,False,False,False,False,False,True,False
1,2,10873.0,1,3,2019,2,10,23,25,2,...,True,False,False,False,False,False,False,False,False,True
2,2,7074.0,3,3,2019,8,40,5,50,2,...,True,False,False,False,False,False,False,False,True,False
3,1,7652.0,3,3,2019,8,40,5,50,2,...,True,False,False,False,False,False,False,False,True,False
4,1,6135.0,3,3,2019,2,10,23,25,2,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13146,2,NaN,3,3,2019,12,35,9,50,2,...,True,False,False,False,False,False,False,False,True,False
13147,1,11793.0,3,3,2019,18,35,16,0,2,...,True,False,False,False,False,False,False,False,True,False
13148,1,9125.0,1,3,2019,9,20,7,5,2,...,False,False,False,False,False,False,False,False,True,False
13149,2,NaN,24,3,2019,22,20,19,40,2,...,True,False,False,False,False,False,False,False,True,False
13150,0,5969.0,6,4,2019,14,20,11,30,2,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,duration_hour,duration_min
0,0,0,5,0,8,10715.0,1,3,2019,8,40,5,50,2,50
1,0,0,5,2,9,10873.0,1,3,2019,2,10,23,25,2,45
2,0,0,5,2,8,7074.0,3,3,2019,8,40,5,50,2,50
3,0,0,5,1,8,7652.0,3,3,2019,8,40,5,50,2,50
4,0,0,5,1,8,6135.0,3,3,2019,2,10,23,25,2,45